import { values } from "lodash";

export const Unit_List = [
  { title: "BAGS(Bag)", value: "Bag", type: "number" },
  { title: "BOTTLES(Btl)", value: "Btl", type: "number" },
  { title: "BOX(Box)", value: "Box", type: "number" },
  { title: "BUNDLES(Bdl)", value: "Bdl", type: "number" },
  { title: "CANS(Can)", value: "Can", type: "number" },
  { title: "CARTONS(Ctn)", value: "Ctn", type: "number" },
  { title: "DOZENS(Dzn)", value: "Dzn", type: "number" },
  { title: "GRAMMES(Gm)", value: "Gm", type: "number" },
  { title: "KILOGRAMS(Kg)", value: "Kg", type: "number" },
  { title: "LITRE(Ltr)", value: "Ltr", type: "number" },
  { title: "METERS(Mtr)", value: "Mtr", type: "number" },
  { title: "MILILITRE(Ml)", value: "Ml", type: "number" },
  { title: "NUMBERS(Nos)", value: "Nos", type: "number" },
  { title: "PACKS(Pac)", value: "Pac", type: "number" },
  { title: "PAIRS(Prs)", value: "Prs", type: "number" },
  { title: "PIECES(Pcs)", value: "Pcs", type: "number" },
  { title: "QUINTAL(Qtl)", value: "Qtl", type: "number" },
  { title: "ROLLS(Rol)", value: "Rol", type: "number" },
  { title: "SQUARE FEET(Sqft)", value: "Sqft", type: "text" },
  { title: "SQUARE Inch(SqIn)", value: "SqIn", type: "text" },
  { title: "Kilogram(kg)", value: "kg", type: "number" },
  { title: "Pieces(Pcs)", value: "Pcs", type: "number" },
  { title: "Gram(g)", value: "g", type: "number" },
  { title: "Metric Ton(tonne)", value: "tonne", type: "number" },
  { title: "Meter(m)", value: "m", type: "number" },
  { title: "Centimeter(cm)", value: "cm" },
  { title: "Millimeter(mm)", value: "mm", type: "number" },
  { title: "Inch(in)", value: "in", type: "number" },
  { title: "Foot(ft)", value: "ft", type: "number" },
  { title: "Cubic Meter(m³)", value: "m3", type: "number" },
  { title: "Liter(L)", value: "L", type: "number" },
  { title: "Milliliter(ml)", value: "ml", type: "number" },
  { title: "Second(s)", value: "s", type: "number" },
  { title: "Minute(min)", value: "min", type: "number" },
  { title: "Hour(hr)", value: "hr", type: "number" },
  { title: "Celsius(°C)", value: "°C", type: "number" },
  { title: "Fahrenheit(°F)", value: "°F", type: "number" },
  { title: "Pascal(Pa)", value: "Pa", type: "number" },
  { title: "Bar(bar)", value: "bar", type: "number" },
  { title: "Meters per Second(m/s)", value: "m/s", type: "number" },
  { title: "Kilometers per Hour(km/h)", value: "km/h", type: "number" },
  { title: "Ampere(A)", value: "A", type: "number" },
  { title: "Volt(V)", value: "V", type: "number" },
  { title: "Watt(W)", value: "W", type: "number" },
  { title: "Kilowatt(kW)", value: "kW", type: "number" },
  { title: "SQUARE CM", value: "Sqcm", type: "text" },
  { title: "SQUARE METER", value: "Sqm", type: "text" },
  // { title: "SIZE", value: "Size", type: "text" },
  // { title: "WEIGHT", value: "weight", type: "number" },
];
